### ISSUE TITLE
Allow switching between different song scenes

### ISSUE THREAD

**Issue by Th0rstenf** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#47]
This should be configurable, e.g. a fixed cycle of X seconds.
On section change base? -> Would need a fallback solution for lazy charters

**Comment by kozaka-tv** [comment]
I hope I get what you wanna have with this ticket! :)

To switch between whitelisted scenes in OBS, I am using the Advanced Scene Switcher plugin:

![image](https://user-images.githubusercontent.com/4964462/228978183-6ee77cef-b876-4695-8026-b3b6b1a97377.png)

With this macros, I can control, how and how fast the Whitelist scenes should be switched. And on is not in the list. This is my guitar cam scene for solos. What could be triggered by channel points or with my foot switch. And also now the Scene switcher switching to this cam in case enterSolo happens, and switch back to the first song scene if leaveSolo.

![image](https://user-images.githubusercontent.com/4964462/228978766-9219d392-fb0b-4b12-b3a5-fa79d71e986f.png)
![image](https://user-images.githubusercontent.com/4964462/228978797-33d204b5-5716-4e71-97b9-c9ef9c9b9115.png)

This is what you want? Because I think, the plugin is better! Because it is really separated from SB and for example, I am switching randomly between 0.3 and 10 seconds. It is way more faster and stable than with SB I think.

Or you mean something else?
--> "Would need a fallback solution for lazy charters". Cam1 if enterChorus? Cam2 if enterRiff? Or maybe this?

**Comment by Th0rstenf** [comment]
The advanced scene switcher is probably more versatile, but this feature was requested as part of the plugin, so let's integrate it.
It's already assigned to me, so no worries. I'll implement a basic functionality for switching, but you can leave it off and use other means if prefered.

**Comment by kozaka-tv** [comment]
There is some problem with this. The conversion into int will drop an Exception if the value could not found in config of the Mock or in SB.

**Comment by Th0rstenf** [comment]
The commits you've added are merged to develop already
