### ISSUE TITLE
Make cooldownPeriod configurable

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#80]
The cooldownPeriod is now set to 3 second hardcoded. It would be better if:
1) this would be configurable by the user
2) if nothing is set, default timeout is 3 seconds

GlobalVariable must have the name: sceneSwitchCooldownPeriod

**Comment by Th0rstenf** [comment]
The cooldown just serves as high pass filter for too quick changes. I don't think that 0 is a useful default value.

Just to repeat it once again:
**It does not act as general delay**
It could be configurable, but honestly as viewer i'd hate to have such quick changes. I don't think that it was ever considered an issue with Warths switcher.

Even if we make it configurable, i'd still say three seconds are a reasonable default value.

**Comment by kozaka-tv** [comment]
I think we should not decide, what the streamer want to have. If 10 seconds, then 10, if the default 3 is ok, 3. If do not want at all, 0. Check a music video :) 2-3 switch in one second :)

Main idea is here to have it configurable at least. Could stay as default on 3.

**Comment by Th0rstenf** [comment]
I already agreed on the configurable part, otherwise I'd have it at least converted to a discussion ;)

I can't think of any music video having three significant changes in a second that is not somewhere between annoying and stupid, That's  a single beat at 180bpm...

We'll just make it configurable and leave the default value. You're right, people can decide themselvels.

For most streamers, this is rather only for getting in and out of breaks too quickly, which can be really annoying. Most streamers won't use multiple scenes for songs anyway 🤷‍♂️

**Comment by kozaka-tv** [comment]
I changed the Description as we discussed. Created a new Discussion regarding this.
